// word-client/src/App.tsx
import React, { useEffect } from "react";
import "./App.scss";
import Loader from "./components/ui/Loader";
import { useAuth } from "./store/auth";

const App: React.FC = () => {
  const { getUser, isLoading } = useAuth();

  useEffect(() => {
    getUser();
  }, [getUser]);

  return (
    <section className="section">
      <div className="container">
        <h1 className="title">Hello World</h1>
        {isLoading && <Loader />}
      </div>
    </section>
  );
};

export default App;

// account-client/src/App.vue
<template>
  <div id="app">
    <section class="section">
      <Loader v-if="loading" class="my-5" />
      <router-view v-else></router-view>
    </section>
  </div>
</template>

<script>
import { onMounted } from "@vue/composition-api";
import { useAuth } from "./store/auth";
import Loader from "./components/ui/Loader";
export default {
  name: "App",
  components: {
    Loader
  },
  setup() {
    const { getUser, loading } = useAuth();

    onMounted(() => {
      getUser();
    });

    return {
      loading
    };
  }
};
</script>

<style lang="scss" scoped></style>
